[package]
name = "slapper"
version = "0.1.0"
authors = ["R. Jacobs <jacobsrudolph@yahoo.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
reqwest = "0.9.11"
serde = { version = "1.0.89", features = ["derive"] }
url = "1.7.2"